# Generated by Django 4.2.27 on 2026-01-31 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_2_answers', to='part_2.question'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_2_ideas', to='part_2.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_2_questions', to='part_2.topic'),
        ),
        migrations.AlterField(
            model_name='topicname',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part_2.topic'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_2_vocabularies', to='part_2.question'),
        ),
    ]
