# Generated by Django 4.2.27 on 2026-01-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0002_alter_answer_question_alter_idea_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='always_in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='from_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='to_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
