# Generated by Django 4.2.27 on 2026-01-31 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0003_topic_always_in_use_topic_from_date_topic_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('free', 'Free'), ('paid', 'Paid'), ('archived', 'Archived'), ('common', 'Common')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_type',
        ),
        migrations.AlterField(
            model_name='topicname',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_2_names', to='part_2.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_type',
            field=models.ManyToManyField(blank=True, to='part_2.topictype'),
        ),
    ]
