# Generated by Django 4.2.27 on 2026-01-31 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0003_topictype_alter_topic_from_date_alter_topic_to_date_and_more'),
        ('part_2', '0004_topictype_alter_topic_from_date_alter_topic_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicname',
            name='part3_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part3_names', to='part_3.topic'),
        ),
    ]
