# Generated by Django 4.2.27 on 2026-02-08 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_2', '0005_alter_topicname_part3_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='speaking/audio/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_2_answers', to='part_2.topic'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_2_ideas', to='part_2.topic'),
        ),
        migrations.AlterField(
            model_name='topictype',
            name='name',
            field=models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('free', 'Free'), ('paid', 'Paid'), ('archived', 'Archived'), ('common', 'Common'), ('not_confirmed_yet', 'Not confirmed yet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_2_vocabularies', to='part_2.topic'),
        ),
    ]
