# Generated by Django 4.2.27 on 2026-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_userachievement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='achievement_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='date_unlocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/images'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='max_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
