# Generated by Django 4.2.27 on 2026-02-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_userachievement_achievement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='achieved_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='date_unlocked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
