# Generated by Django 4.2.27 on 2026-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_userachievement_achieved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
