# Generated by Django 4.2.27 on 2026-02-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_achievement_userachievedat_delete_userachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='userachievedat',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
