# Generated by Django 4.2.27 on 2026-02-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_remove_achievement_quantity_userachievedat_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievedat',
            name='achieved_at',
            field=models.JSONField(default=list),
        ),
    ]
