# Generated by Django 4.2.27 on 2026-02-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_alter_userachievedat_achieved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievedat',
            name='achieved_at',
        ),
        migrations.AddField(
            model_name='userachievedat',
            name='achievements_date',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
