# Generated by Django 4.2.27 on 2026-01-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_writing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writingessay',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writingfeedback',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/writing/'),
        ),
    ]
