# Generated by Django 4.2.27 on 2026-01-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_writing', '0002_alter_writingessay_text_alter_writingfeedback_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writingessay',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='writingfeedback',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='writingtask',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='writingtask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='writing/images'),
        ),
    ]
