# Generated by Django 4.2.27 on 2026-01-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('overall_band', models.FloatField()),
                ('tr', models.FloatField()),
                ('cc', models.FloatField()),
                ('lr', models.FloatField()),
                ('gra', models.FloatField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1', 'Task 1'), ('task2', 'Task 2')], max_length=5)),
                ('topic', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing/images')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WritingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='candidates_writing.writingessay')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='writingessay',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essays', to='candidates_writing.writingtask'),
        ),
    ]
