# Generated by Django 4.2.27 on 2026-01-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_writing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WritingEssay',
            new_name='Essay',
        ),
        migrations.RenameModel(
            old_name='WritingFeedback',
            new_name='Feedback',
        ),
        migrations.RenameModel(
            old_name='WritingTask',
            new_name='Task',
        ),
    ]
