# Generated by Django 4.2.27 on 2026-01-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0002_alter_answer_question_alter_idea_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('free', 'Free'), ('paid', 'Paid'), ('archived', 'Archived'), ('common', 'Common')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_type',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_type',
            field=models.ManyToManyField(blank=True, to='part_3.topictype'),
        ),
    ]
