# Generated by Django 4.2.27 on 2026-02-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_3', '0003_topictype_alter_topic_from_date_alter_topic_to_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='speaking/audio/'),
        ),
        migrations.AlterField(
            model_name='topictype',
            name='name',
            field=models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('free', 'Free'), ('paid', 'Paid'), ('archived', 'Archived'), ('common', 'Common'), ('not_confirmed_yet', 'Not confirmed yet')], max_length=50),
        ),
    ]
