# Generated by Django 4.2.27 on 2026-01-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steaks', '0003_remove_steak_count_steak_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steak',
            options={'ordering': ('id',)},
        ),
    ]
