# Generated by Django 4.2.27 on 2026-01-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('part', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], max_length=5)),
                ('topic_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='experts_speaking.speakingquestion')),
            ],
        ),
        migrations.AddField(
            model_name='speakingquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='experts_speaking.speakingtopic'),
        ),
        migrations.CreateModel(
            name='SpeakingIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='experts_speaking.speakingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='speaking/audio/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='experts_speaking.speakingquestion')),
            ],
        ),
    ]
