# Generated by Django 4.2.27 on 2026-01-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='speaking/audio/')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('part', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], max_length=5)),
                ('topic_type', models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('free', 'Free'), ('paid', 'Paid'), ('archived', 'Archived')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic_type', models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('free', 'Free'), ('paid', 'Paid'), ('archived', 'Archived')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='experts_speaking.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='experts_speaking.topicquestion')),
            ],
        ),
        migrations.RemoveField(
            model_name='speakingquestion',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='speakingvocabulary',
            name='question',
        ),
        migrations.RenameModel(
            old_name='SpeakingIdea',
            new_name='Idea',
        ),
        migrations.DeleteModel(
            name='SpeakingAnswer',
        ),
        migrations.DeleteModel(
            name='SpeakingQuestion',
        ),
        migrations.DeleteModel(
            name='SpeakingTopic',
        ),
        migrations.DeleteModel(
            name='SpeakingVocabulary',
        ),
        migrations.AddField(
            model_name='speakingpart',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_topic', to='experts_speaking.topic'),
        ),
        migrations.AddField(
            model_name='speakingexam',
            name='part1',
            field=models.ForeignKey(limit_choices_to={'part': 'part1'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_part1', to='experts_speaking.speakingpart'),
        ),
        migrations.AddField(
            model_name='speakingexam',
            name='part2',
            field=models.ForeignKey(limit_choices_to={'part': 'part2'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_part2', to='experts_speaking.speakingpart'),
        ),
        migrations.AddField(
            model_name='speakingexam',
            name='part3',
            field=models.ForeignKey(limit_choices_to={'part': 'part3'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_part3', to='experts_speaking.speakingpart'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='experts_speaking.topicquestion'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='experts_speaking.topicquestion'),
        ),
    ]
