# Generated by Django 4.2.27 on 2026-01-29 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experts_speaking', '0002_answer_speakingexam_speakingpart_topic_topicquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='static/speaking/audio/'),
        ),
    ]
