# Generated by Django 4.2.27 on 2026-01-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0003_answer_teacher_alter_answer_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingpart',
            name='topic_type',
        ),
    ]
