# Generated by Django 4.2.27 on 2026-01-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0004_remove_speakingpart_topic_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicQuestion',
            new_name='Question',
        ),
        migrations.AddField(
            model_name='speakingpart',
            name='is_part_2',
            field=models.BooleanField(default=False),
        ),
    ]
