# Generated by Django 4.2.27 on 2026-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0005_rename_topicquestion_question_speakingpart_is_part_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingpart',
            name='main_question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
