# Generated by Django 4.2.27 on 2026-01-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0006_speakingpart_main_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingpart',
            name='is_part_2',
        ),
    ]
