# Generated by Django 4.2.27 on 2026-01-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0007_remove_speakingpart_is_part_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='speaking/audio/'),
        ),
    ]
