# Generated by Django 4.2.27 on 2026-01-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0008_alter_answer_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingPartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_names', to='experts_speaking.speakingpart')),
            ],
        ),
    ]
