# Generated by Django 4.2.27 on 2026-01-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0009_speakingpartname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakingpartname',
            old_name='name',
            new_name='topic_name',
        ),
    ]
