# Generated by Django 4.2.27 on 2026-01-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0010_rename_name_speakingpartname_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='speakingexam',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='speakingpart',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='speakingpartname',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ('id',)},
        ),
    ]
