# Generated by Django 4.2.27 on 2026-01-31 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('experts_speaking', '0011_alter_answer_options_alter_idea_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingpart',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='speakingpartname',
            name='part_name',
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='topic',
            name='main_question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='part',
            field=models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3')], default='part1', max_length=5),
        ),
        migrations.DeleteModel(
            name='SpeakingExam',
        ),
        migrations.DeleteModel(
            name='SpeakingPart',
        ),
        migrations.DeleteModel(
            name='SpeakingPartName',
        ),
    ]
