# Generated by Django 4.2.27 on 2026-01-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_interads_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interads',
            options={'ordering': ('id',)},
        ),
    ]
