# Generated by Django 4.2.27 on 2026-02-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_interads_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interads',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interads',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
