# Generated by Django 4.2.27 on 2026-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_interads_end_date_alter_interads_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inter_ad_images/'),
        ),
        migrations.AlterField(
            model_name='interads',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
