# Generated by Django 4.2.27 on 2026-01-27 06:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendlist',
            unique_together={('user', 'friend')},
        ),
    ]
