# Generated by Django 4.2.27 on 2026-01-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendlist',
            unique_together=set(),
        ),
    ]
