# Generated by Django 4.2.27 on 2026-01-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friendlist_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlist',
            options={'ordering': ('id',)},
        ),
    ]
