# Generated by Django 4.2.27 on 2026-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='steaks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
