# Generated by Django 4.2.27 on 2026-01-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_avatar_alter_user_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.CharField(choices=[('default', 'Default'), ('1_month', '1 Month'), ('3_month', '3 Month'), ('12_month', '12 Month')], default='default', max_length=255),
        ),
    ]
