# Generated by Django 4.2.27 on 2026-01-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
