# Generated by Django 4.2.27 on 2026-01-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
