# Generated by Django 4.2.27 on 2026-01-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
