# Generated by Django 4.2.27 on 2026-01-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
    ]
