# Generated by Django 4.2.27 on 2026-01-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
