# Generated by Django 4.2.27 on 2026-01-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_uuid_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
