# Generated by Django 4.2.27 on 2026-01-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_passwordresetotp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, editable=False, max_length=254, unique=True),
        ),
    ]
