# Generated by Django 4.2.27 on 2026-01-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reward',
            field=models.PositiveIntegerField(default=5, help_text='InterCoin reward for this user.'),
        ),
    ]
