# Generated by Django 4.2.27 on 2026-01-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
