# Generated by Django 4.2.27 on 2026-01-15 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=10, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/')),
                ('phone_model', models.CharField(blank=True, max_length=255)),
                ('instagram', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('speaking_band', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reading_band', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('listening_band', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('writing_band', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('trf_number', models.CharField(blank=True, max_length=100)),
                ('trf_date', models.DateField(blank=True, null=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('reward', models.PositiveIntegerField(default=5, help_text='InterCoin reward for this user added via referral.')),
                ('is_premium', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_uuid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
