# Generated by Django 4.2.27 on 2026-01-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_steaks_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
