# Generated by Django 4.2.27 on 2026-01-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steaks', '0002_alter_steak_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steak',
            name='count',
        ),
        migrations.AddField(
            model_name='steak',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
