# Generated by Django 4.2.27 on 2026-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interads',
            name='ad_type',
            field=models.CharField(blank=True, choices=[('full', 'FullScreen'), ('mini', 'Mini')], max_length=255, null=True),
        ),
    ]
