# Generated by Django 4.2.27 on 2026-01-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_interads_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/inter_ad_images/'),
        ),
    ]
