# Generated by Django 4.2.27 on 2026-01-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_speaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakingpart',
            name='exam_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='QuestionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_date', to='candidates_speaking.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_count', models.PositiveIntegerField(default=0)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_name', to='candidates_speaking.speakingpart')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_exam_name', to='candidates_speaking.question')),
            ],
        ),
    ]
