# Generated by Django 4.2.27 on 2026-01-29 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_speaking', '0002_question_date_speakingpart_exam_center_questiondate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='questiondate',
            name='question',
        ),
        migrations.RemoveField(
            model_name='speakingpart',
            name='exam_center',
        ),
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_questions', to='candidates_speaking.topic'),
        ),
        migrations.DeleteModel(
            name='ExamName',
        ),
        migrations.DeleteModel(
            name='QuestionDate',
        ),
        migrations.AddField(
            model_name='questionexamname',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_exam_name', to='candidates_speaking.question'),
        ),
    ]
