# Generated by Django 4.2.27 on 2026-01-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcard_definition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='words',
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/flash_cards_images/')),
                ('flash_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_cards', to='flashcards.flashcard')),
            ],
        ),
    ]
