# Generated by Django 4.2.27 on 2026-01-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_remove_flashcard_definition_remove_flashcard_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='wordlist',
            options={'ordering': ('id',)},
        ),
    ]
