# Generated by Django 4.2.27 on 2026-01-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_flashcard_options_alter_wordlist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flash_cards_images/'),
        ),
    ]
