# Generated by Django 4.2.27 on 2026-02-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='plan',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('1_month', '1 Month'), ('3_month', '3 Month'), ('12_month', '12 Month')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
