# Generated by Django 4.2.27 on 2026-01-31 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_1_answers', to='part_1.question'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_1_ideas', to='part_1.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_1_questions', to='part_1.topic'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_1_vocabularies', to='part_1.question'),
        ),
    ]
