# Generated by Django 4.2.27 on 2026-01-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0003_topictype_remove_topic_topic_type_topic_topic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_type',
            field=models.ManyToManyField(blank=True, to='part_1.topictype'),
        ),
        migrations.AlterField(
            model_name='topictype',
            name='name',
            field=models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('free', 'Free'), ('paid', 'Paid'), ('archived', 'Archived')], max_length=50),
        ),
    ]
