# Generated by Django 4.2.27 on 2026-01-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0004_alter_topic_topic_type_alter_topictype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
