# Generated by Django 4.2.27 on 2026-01-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part_1', '0005_alter_topic_from_date_alter_topic_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictype',
            name='name',
            field=models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('free', 'Free'), ('paid', 'Paid'), ('archived', 'Archived'), ('common', 'Common')], max_length=50),
        ),
    ]
