# Generated by Django 4.2.27 on 2026-01-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_flash_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/flash_cards_images/'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
